import java.util.ArrayList;
import java.util.Scanner;

/** Runs the DUDE command-line application. */
public class Dude {
    /** Starts the application and processes commands entered by the user. */
    public static void main(String[] args) {
        // Banner generated by ChatGPT but edited manually to align better
        String banner = "██████╗  ██╗   ██╗ ██████╗  ███████╗\n"
                + "██╔══██╗ ██║   ██║ ██╔══██╗ ██╔════╝\n"
                + "██║  ██║ ██║   ██║ ██║  ██║ █████╗\n"
                + "██║  ██║ ██║   ██║ ██║  ██║ ██╔══╝\n"
                + "██████╔╝ ╚██████╔╝╚██████╔╝ ███████╗\n"
                + "╚═════╝   ╚═════╝ ╚══════╝  ╚══════╝";

        int width = getTerminalWidth();
        String border = "─".repeat(width);

        printBox(border, banner, "Hello! I'm DUDE.", "What can I do for you?");

        try (Scanner scanner = new Scanner(System.in)) {
            onUpdate(scanner, border, new ArrayList<>());
        }
    }

    /** Processes commands until the user enters the exit command or input ends. */
    private static void onUpdate(Scanner scanner, String border, ArrayList<String> tasks) {
        while (scanner.hasNextLine()) {
            String command = scanner.nextLine();

            switch (command) {
                case "bye":
                    printBox(border, "Bye. Hope to see you again soon!");
                    return;
                case "list":
                    printTaskList(border, tasks);
                    break;
                default:
                    tasks.add(command);
                    printBox(border, "added: " + command);
                    break;
            }
        }
    }

    /** Prints all stored tasks with their one-based positions. */
    private static void printTaskList(String border, ArrayList<String> tasks) {
        String[] taskLines = new String[tasks.size()];
        for (int i = 0; i < tasks.size(); i++) {
            taskLines[i] = (i + 1) + ". " + tasks.get(i);
        }
        printBox(border, taskLines);
    }

    /** Returns the terminal width, or a default width when it cannot be determined. */
    private static int getTerminalWidth() {
        try {
            var console = System.console();
            if (console != null) {
                var method = console.getClass().getMethod("getWidth");
                return (int) method.invoke(console);
            }
        } catch (Exception ignored) {
        }
        return 60;
    }

    /** Prints the supplied lines between two borders. */
    private static void printBox(String border, String... lines) {
        System.out.println(border);
        for (String line : lines) {
            for (String part : line.split("\n")) {
                System.out.println(padRight(part, border.length()));
            }
        }
        System.out.println(border);
    }

    /** Returns the supplied text padded with spaces to the requested length. */
    private static String padRight(String s, int length) {
        return s.length() >= length ? s : s + " ".repeat(length - s.length());
    }
}
