import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import exception.UsageException;
import task.Deadline;
import task.Event;
import task.Task;
import task.Todo;

/** Runs the DUDE command-line application. */
public class Dude {
    private static final String RED = "\u001B[31m";
    private static final String RESET = "\u001B[0m";

    private static final HashMap<String, String> USAGE_MESSAGES = new HashMap<>(Map.of(
            "mark", "Usage: mark <task number>",
            "unmark", "Usage: unmark <task number>",
            "todo", "Usage: todo <task details>",
            "deadline", "Usage: deadline <description> /by <date or time>",
            "event", "Usage: event <description> /from <start> /to <end>"));
    private static final String TASK_USAGE = "Usage: todo <task details> | deadline <description> /by <date or time>"
            + " | event <description> /from <start> /to <end>";

    /** Starts the application and processes commands entered by the user. */
    public static void main(String[] args) {
        // Banner generated by ChatGPT but edited manually to align better
        String banner = "██████╗  ██╗   ██╗ ██████╗  ███████╗\n"
                + "██╔══██╗ ██║   ██║ ██╔══██╗ ██╔════╝\n"
                + "██║  ██║ ██║   ██║ ██║  ██║ █████╗\n"
                + "██║  ██║ ██║   ██║ ██║  ██║ ██╔══╝\n"
                + "██████╔╝ ╚██████╔╝╚██████╔╝ ███████╗\n"
                + "╚═════╝   ╚═════╝ ╚══════╝  ╚══════╝";

        int width = getTerminalWidth();
        String border = "─".repeat(width);

        printBox(border, banner, "Hello! I'm DUDE.", "What can I do for you?");

        try (Scanner scanner = new Scanner(System.in)) {
            onUpdate(scanner, border, new ArrayList<>());
        }
    }

    /** Processes commands until the user enters the exit command or input ends. */
    private static void onUpdate(Scanner scanner, String border, ArrayList<Task> tasks) {
        while (scanner.hasNextLine()) {
            String input = scanner.nextLine();
            String[] commandParts = input.trim().split("\\s+", 2);
            String action = commandParts[0];
            String argument = commandParts.length > 1 ? commandParts[1] : null;

            try {
                switch (action) {
                    case "bye":
                        printBox(border, "Bye. Hope to see you again soon!");
                        return;
                    case "list":
                        printTaskList(border, tasks);
                        break;
                    case "mark", "unmark":
                        updateTask(border, tasks, action, argument);
                        break;
                    case "todo", "deadline", "event":
                        addTask(border, tasks, action, argument);
                        break;
                    default:
                        throw new UsageException(action, "command", action,
                                "todo, deadline, or event", TASK_USAGE, "<task type>");
                }
            } catch (UsageException e) {
                printError(border, e);
            }
        }
    }

    /** Marks or unmarks the task identified by a one-based task number. */
    private static void updateTask(String border, ArrayList<Task> tasks,
                                   String action, String argument) throws UsageException {
        if (argument == null || argument.isBlank()) {
            throw usageError(action, "task number", "<missing>", "an integer", "<task number>");
        }

        int taskNumber;
        try {
            taskNumber = Integer.parseInt(argument);
        } catch (NumberFormatException e) {
            throw usageError(action, "task number", argument, "an integer", "<task number>", e);
        }

        int taskIndex = taskNumber - 1;
        if (taskIndex < 0 || taskIndex >= tasks.size()) {
            throw usageError(action, "task number", argument,
                    "an existing task number", "<task number>");
        }

        Task task = tasks.get(taskIndex);
        String[] messageLines = switch (action) {
            case "mark" -> {
                task.markAsDone();
                yield new String[] {
                    "Nice! I've marked this task as done:",
                    "  " + task
                };
            }
            case "unmark" -> {
                task.markAsNotDone();
                yield new String[] {
                    "OK, I've marked this task as not done yet:",
                    "  " + task
                };
            }
            default -> throw new IllegalArgumentException("Unsupported task action: " + action);
        };
        printBox(border, messageLines);
    }

    /** Creates and stores a task from a typed task command. */
    private static void addTask(String border, ArrayList<Task> tasks,
                                String action, String argument) throws UsageException {
        Task task;
        switch (action) {
            case "todo":
                task = Todo.fromInput(argument);
                break;
            case "deadline":
                task = Deadline.fromInput(argument);
                break;
            case "event":
                task = Event.fromInput(argument);
                break;
        default:
            throw new IllegalArgumentException("Unsupported task type: " + action);
        }

        tasks.add(task);
        printBox(border,
                "Got it. I've added this task:",
                "  " + task,
                String.format("Now you have %d tasks in the list.", tasks.size()));
    }

    private static UsageException usageError(String action, String fieldName,
                                             String actualValue, String expectedType,
                                             String usageToken) {
        return new UsageException(action, fieldName, actualValue, expectedType,
                USAGE_MESSAGES.get(action), usageToken);
    }

    private static UsageException usageError(String action, String fieldName,
                                             String actualValue, String expectedType,
                                             String usageToken, Throwable cause) {
        return new UsageException(action, fieldName, actualValue, expectedType,
                USAGE_MESSAGES.get(action), usageToken, cause);
    }

    /** Prints a customized error and the usage message for an invalid command. */
    private static void printError(String border, UsageException e) {
        String usage = e.getUsageMessage().replace(
                e.getUsageToken(), RED + e.getUsageToken() + RESET);
        printBox(border,
                String.format("Error: invalid %s %s for %s.", e.getFieldName(),
                        e.getActualValue(), e.getAction()),
                String.format("Expected: %s.", e.getExpectedType()),
                usage);
    }

    /** Prints all stored tasks with their one-based positions. */
    private static void printTaskList(String border, ArrayList<Task> tasks) {
        String[] taskLines = Stream.concat(
                Stream.of("Here are the tasks in your list:"),
                IntStream.range(0, tasks.size())
                .mapToObj(i -> String.format("%d.%s", i + 1, tasks.get(i))))
                .toArray(String[]::new);
        printBox(border, taskLines);
    }

    /** Returns the terminal width, or a default width when it cannot be determined. */
    private static int getTerminalWidth() {
        try {
            var console = System.console();
            if (console != null) {
                var method = console.getClass().getMethod("getWidth");
                return (int) method.invoke(console);
            }
        } catch (Exception ignored) {
        }
        return 60;
    }

    /** Prints the supplied lines between two borders. */
    private static void printBox(String border, String... lines) {
        System.out.println(border);
        for (String line : lines) {
            for (String part : line.split("\n")) {
                System.out.println(padRight(part, border.length()));
            }
        }
        System.out.println(border);
    }

    /** Returns the supplied text padded with spaces to the requested length. */
    private static String padRight(String s, int length) {
        return s.length() >= length ? s : s + " ".repeat(length - s.length());
    }
}
